export const teamData = [

{
  id: "37ced2b8-88fc-40b9-bd67-2f191a8c6879",
  name: "Ann",
  role: "Coach, Heilpraktikerin für Psychotherapie, Hypnose Coach",
  qualificationLevel: 5,
  image: "https://mypoise.de/wp-content/uploads/2023/01/DSC_0007-copy-2-1300x1300.jpg",
  video: "https://youtu.be/rWhc4JvVmaw",
  email: "ann.woeste@web.de",
  short: "Ich begleite Menschen, die innere Anspannung, Unsicherheit oder emotionale Überforderung erleben. Mein Ansatz ist ruhig, direkt und klar strukturiert, mit Fokus auf Selbstregulation und Stärkung der persönlichen Handlungsfähigkeit.",
  themes: {
    selbstwert: 3,
    stress: 3,
    burnout: 2,
    angst_panik: 2,
    beziehung: 1,
    depressive_verstimmung: 1,
    beruf_orientierung: 1,
  },
  keywords: [
    "selbstwert","selbstvertrauen","ich bin nicht gut genug","selbstzweifel",
    "stress","innere anspannung","überforderung","schlafprobleme",
    "burnout","erschöpfung","leistungsdruck",
    "angst","panik","herzrasen","atemnot",
    "beziehung","konflikte","beruf","arbeitsbelastung",
    "hypnose","systemisch","lösungsorientiert"
  ],
  preis_std: 150,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/75f62df4c63554a1436d49c3a381da84502728a0457c9c8b56d30e21fa5021c5%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 4,
  beruf_ziele_orientierung: 2,
  stress: 0,
  burnout: 2,
  depressive_verstimmung: 0,
  angst_panik: 0,
  selbstwert_selbstliebe: 4,
  emotionales_essen: 0,
  krankheit_psychosomatik: 0,
  angehoerige: 2,
  sexualitaet: 0,
  trauer: 2,
},
},

{
  id: "22be71f8-8b1d-4cb7-9434-8cd4f4bd03f4",
  name: "Anna",
  role: "Psychologin, Psychotherapeutin",
  qualificationLevel: 1,
  image: "https://mypoise.de/wp-content/uploads/2023/06/Anna-Moser-scaled-e1739306168495-1300x1300.jpg",
  video: "https://youtu.be/I6a4ZUM5KiU",
  short: "Ich unterstütze Menschen in herausfordernden Lebensphasen, insbesondere bei emotionaler Belastung und Erschöpfung.",
  themes: {
    stress: 3,
    burnout: 3,
    depressive_verstimmung: 2,
    selbstwert: 2,
    angst_panik: 1,
    krankheit_verlust: 1,
    lebensphase: 2,
  },
  keywords: [
    "stress","erschöpfung","burnout","traurigkeit","antriebslosigkeit",
    "selbstwert","unsicherheit","lebenskrise","neuorientierung"
  ],
  preis_std: 200,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/db284e0dfb24a13214628dc2264f2e997617ef505a9da7a47d7c5b9d6dbd3b62%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 4,
  beruf_ziele_orientierung: 1,
  stress: 4,
  burnout: 4,
  depressive_verstimmung: 2,
  angst_panik: 2,
  selbstwert_selbstliebe: 4,
  emotionales_essen: 2,
  krankheit_psychosomatik: 0,
  angehoerige: 0,
  sexualitaet: 0,
  trauer: 2,
},
},

{
  id: "c447f910-eb92-4f62-97fa-595c32b479c1",
  name: "Anja",
  role: "Psychologin, Psychotherapeutin in Ausbildung",
  qualificationLevel: 3,
  image: "https://mypoise.de/wp-content/uploads/2022/11/Vorstellungsfoto-1300x1300.jpg",
  video: "https://youtu.be/23tko9Jdr3A",
  short: "Ich begleite Menschen, die sich im inneren Konflikt befinden, sich emotional erschöpft fühlen oder eine Neuorientierung suchen.",
  themes: {
    selbstwert: 3,
    stress: 2,
    depressive_verstimmung: 2,
    beruf_orientierung: 2,
    beziehung: 2,
    angst_panik: 1,
  },
  keywords: [
    "selbstwert","selbstzweifel","unsicherheit",
    "stress","überforderung",
    "neuorientierung","sinnfrage",
    "beziehung","konflikte"
  ],
  preis_std: 180,
  preis_ermaessigt: 150,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/67e9cf48e7519924f64e65591678c2a24c87f3f4cf7e66c79a5a6c856205083f%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 2,
  beruf_ziele_orientierung: 2,
  stress: 2,
  burnout: 2,
  depressive_verstimmung: 2,
  angst_panik: 2,
  selbstwert_selbstliebe: 4,
  emotionales_essen: 2,
  krankheit_psychosomatik: 1,
  angehoerige: 2,
  sexualitaet: 0,
  trauer: 2,
},
},

{
  id: "b38de80a-7f34-41c2-aac7-d42a4f6f350a",
  name: "Babette",
  role: "Psychologin, Hypnose Coach",
  qualificationLevel: 4,
  image: "https://mypoise.de/wp-content/uploads/2022/11/IMG_7891-scaled-e1669712492385-700x700.jpeg",
  video: "https://youtu.be/ooreni-vA78",
  short: "Ich arbeite schwerpunktmäßig mit Menschen, die unter Stress, Überforderung oder anhaltender innerer Anspannung leiden.",
  themes: {
    stress: 3,
    burnout: 2,
    angst_panik: 2,
    psychosomatik: 2,
    selbstwert: 1,
  },
  keywords: [
    "stress","überforderung","burnout",
    "angst","innere unruhe",
    "psychosomatik","spannung"
  ],
  preis_std: 160,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/a950b84b7fcb581bf1de6d341275ffee44f3dc9ff3ea621833d9cd69edff56e0%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 4,
  beruf_ziele_orientierung: 0,
  stress: 2,
  burnout: 2,
  depressive_verstimmung: 2,
  angst_panik: 4,
  selbstwert_selbstliebe: 4,
  emotionales_essen: 2,
  krankheit_psychosomatik: 0,
  angehoerige: 2,
  sexualitaet: 2,
  trauer: 2,
},
},
{
    id: "e2921aee-2d2b-43dc-9644-ddb2b7ff6f69",
  name: "Carolin",
  role: "Psychologin, Systemischer Coach",
  qualificationLevel: 4,
  image: "https://mypoise.de/wp-content/uploads/2023/09/163_Portrait-Juni2023__pp-1300x1300.jpg",
  video: "https://youtu.be/bjJ76067_j0",
  short:
    "Ich begleite Menschen in Umbruchphasen oder inneren Übergängen und unterstütze dabei, emotionale Orientierung und Stabilität zu entwickeln.",
  themes: {
    lebensphase: 3,
    beruf_orientierung: 3,
    selbstwert: 2,
    stress: 2,
    depressive_verstimmung: 1,
    beziehung: 1,
  },
  keywords: [
    "umbruch","lebensveränderung","neu anfangen","orientierungslosigkeit",
    "berufliche neuorientierung","jobwechsel","entscheidung treffen",
    "selbstwert","innere klarheit",
    "stress","innere unruhe",
    "systemisch","ressourcenorientiert"
  ],
  preis_std: 160,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/93fad123ee38ccfa2f9a25423889e2b941c943c7679f2259dbb322387ce0f98b%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 0,
  beruf_ziele_orientierung: 4,
  stress: 4,
  burnout: 0,
  depressive_verstimmung: 4,
  angst_panik: 0,
  selbstwert_selbstliebe: 4,
  emotionales_essen: 0,
  krankheit_psychosomatik: 0,
  angehoerige: 4,
  sexualitaet: 0,
  trauer: 0,
},
},

{
    id: "e747b777-7e8a-43a9-a244-a67f59cf4227",
  name: "Caroline",
  role: "Ärztin (Gynäkologie), Psychotherapeutin",
  qualificationLevel: 1,
  image: "https://mypoise.de/wp-content/uploads/2023/12/IMG_7279-700x700.jpg",
  video: "https://youtu.be/xvDbQYWlpL8",
  short:
    "Ich begleite Menschen bei psychosomatischen Themen, wenn Körper und Emotionen eng miteinander verbunden sind.",
  themes: {
    psychosomatik: 3,
    stress: 2,
    angst_panik: 2,
    depressive_verstimmung: 2,
    selbstwert: 1,
    erschöpfung: 2,
  },
  keywords: [
    "psychosomatik","körperliche symptome","körper und psyche",
    "zyklusbeschwerden","hormone",
    "stress","erschöpfung",
    "angst","innere unruhe",
    "körperorientiert","achtsamkeit"
  ],
  preis_std: 170,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/a6b036ba257178278f5c92b72e04e9120ea076157959112266c8ec220ed2217f%40group.calendar.google.com/public/basic.ics",
  scores: {
  partnerschaft_beziehung: 0,
  beruf_ziele_orientierung: 5,
  stress: 4,
  burnout: 0,
  depressive_verstimmung: 4,
  angst_panik: 5,
  selbstwert_selbstliebe: 4,
  emotionales_essen: 0,
  krankheit_psychosomatik: 0,
  angehoerige: 4,
  sexualitaet: 2,
  trauer: 0,
},
},

{
    id: "94e1f527-b80e-42b5-9bbd-a52342f1c216",
  name: "Elena",
  role: "Psychologin, Coach",
  qualificationLevel: 4,
  image: "https://mypoise.de/wp-content/uploads/2025/02/Image-scaled-e1740223110391.jpeg",
  video: "https://youtu.be/Gbmggqdwl9M",
  short:
    "Ich unterstütze Menschen, die funktionieren müssen, obwohl innerlich vieles schwer ist, und helfe dabei, wieder in Kontakt mit sich selbst zu kommen.",
  themes: {
    stress: 3,
    burnout: 3,
    selbstwert: 2,
    depressive_verstimmung: 2,
    selbstkontakt: 3,
  },
  keywords: [
    "funktionieren","dauerbelastung","stress",
    "burnout","erschöpfung","keine energie",
    "selbstkontakt","innere leere",
    "achtsamkeit","stabilisierung"
  ],
  preis_std: 150,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/3fa5a5955038a6f744313415c7f2052720ff0cc72cc61245dcfca9207e92411f%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 4,
  beruf_ziele_orientierung: 2,
  stress: 4,
  burnout: 4,
  depressive_verstimmung: 4,
  angst_panik: 4,
  selbstwert_selbstliebe: 4,
  emotionales_essen: 0,
  krankheit_psychosomatik: 2,
  angehoerige: 4,
  sexualitaet: 2,
  trauer: 2,
},
},

{
    id: "04722d1b-e321-4322-8276-3595f070ee4c",
  name: "Franziska",
  role: "Psychologin, Psychotherapeutin in Ausbildung, Psychoonkologin",
  qualificationLevel: 3,
  image: "https://mypoise.de/wp-content/uploads/2022/12/1654680310653.jpg",
  video: "https://youtu.be/kngeVsC0vec",
  short:
    "Ich begleite Menschen bei Krankheit, Verlust oder seelischer Erschöpfung und biete Halt und Orientierung in belastenden Lebensphasen.",
  themes: {
    krankheit_verlust: 3,
    trauer: 3,
    erschöpfung: 2,
    depressive_verstimmung: 2,
    stabilisierung: 3,
  },
  keywords: [
    "krankheit","diagnose","lebenskrise",
    "trauer","verlust","abschied",
    "erschöpfung","keine kraft",
    "stabilisierung","halt","sicherheit"
  ],
  preis_std: 150,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/ca7d425f824b9b777b6ba5697cc7b905d7bec811f7b4839a54fa1ce318587ed2%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 4,
  beruf_ziele_orientierung: 0,
  stress: 4,
  burnout: 2,
  depressive_verstimmung: 4,
  angst_panik: 0,
  selbstwert_selbstliebe: 4,
  emotionales_essen: 0,
  krankheit_psychosomatik: 4,
  angehoerige: 4,
  sexualitaet: 0,
  trauer: 4,
},
},
{
    id: "64699791-6203-416e-bab9-6abe043ac454",
  name: "Gerhard",
  role: "Coach, systemischer Berater, Mediator",
  qualificationLevel: 6,
  image: "https://mypoise.de/wp-content/uploads/2025/04/Frontfoto-1024x1024.jpg",
  video: "https://youtu.be/sEhRwOirFZ0",
  short:
    "Ich arbeite mit Menschen in inneren und zwischenmenschlichen Konflikten und unterstütze dabei, Klarheit und handlungsfähige Perspektiven zu entwickeln.",
  themes: {
    beziehung: 3,
    konflikt: 3,
    selbstwert: 2,
    beruf_orientierung: 2,
    stress: 1,
  },
  keywords: [
    "konflikt","streit","spannung","verstrickung",
    "beziehung","partnerschaft","kommunikationsprobleme","abgrenzung",
    "selbstwirksamkeit","handlungsfähigkeit","klarheit",
    "konflikte im job","führung",
    "systemisch","mediation","lösungsorientiert"
  ],
  preis_std: 160,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/337c7badcffe966991eb34f4b885fcffffba011562b751a085383346708d6263%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 1,
  beruf_ziele_orientierung: 5,
  stress: 4,
  burnout: 2,
  depressive_verstimmung: 4,
  angst_panik: 5,
  selbstwert_selbstliebe: 4,
  emotionales_essen: 4,
  krankheit_psychosomatik: 0,
  angehoerige: 0,
  sexualitaet: 0,
  trauer: 0,
},
},

{
    id: "a17d2f7d-64e4-4e3d-be42-e26755c62eb3",
  name: "Gesine",
  role: "Psychologin, Psychotherapeutin",
  qualificationLevel: 2,
  image: "https://mypoise.de/wp-content/uploads/2025/08/Bildschirmfoto-2025-08-04-um-14.55.22.png",
  video: "https://youtu.be/oLn_qmHA2vk",
  short:
    "Ich begleite Menschen mit innerer Anspannung, Traurigkeit oder emotionaler Überlastung und helfe dabei, wieder Stabilität und Sicherheit zu finden.",
  themes: {
    depressive_verstimmung: 3,
    angst_panik: 2,
    stress: 2,
    selbstwert: 2,
    stabilisierung: 3,
  },
  keywords: [
    "depressive verstimmung","traurigkeit","hoffnungslosigkeit","innere leere",
    "angst","innere unruhe","überforderung",
    "nervensystem","emotionale sicherheit","stabilisierung",
    "selbstwert","selbstfürsorge"
  ],
  preis_std: 180,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/f3f21fee63e77164d204d3fd0f296e64837dccf4242a6b3f9482f1ba842fedab%40group.calendar.google.com/public/basic.ics",
  scores: {
    partnerschaft_beziehung: 0,
    beruf_ziele_orientierung: 0,
    stress: 0,
    burnout: 0,
    depressive_verstimmung: 0,
    angst_panik: 0,
    selbstwert_selbstliebe: 0,
    emotionales_essen: 0,
    krankheit_psychosomatik: 0,
    angehoerige: 0,
    sexualitaet: 4,
    trauer: 0,
  },
},

{
    id: "770c9df6-1cad-4404-b98a-e07ad332c2cc",
  name: "Isabella",
  role: "Klinische Psychologin",
  qualificationLevel: 2,
  image: "https://mypoise.de/wp-content/uploads/2024/08/IsabellaKusztrits%C2%A9DanielaGruber-13.jpeg-600x426.png",
  video: "",
  short:
    "Ich begleite hochsensible Menschen dabei, ihre Emotionen zu verstehen, gesunde Grenzen zu entwickeln und innere Stabilität aufzubauen.",
  themes: {
    hochsensibilität: 3,
    selbstwert: 3,
    emotionale_regulation: 3,
    beziehung: 2,
    stress: 1,
  },
  keywords: [
    "hochsensibilität","reizüberflutung","zu sensibel",
    "emotionale regulation","überwältigende emotionen",
    "selbstwert","selbstannahme",
    "grenzen setzen","abgrenzung"
  ],
  preis_std: 170,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/8e6975d60569a919f44359f9e7272f66b2345b1aa29b2f391ac2237e092e7994%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 2,
  beruf_ziele_orientierung: 0,
  stress: 4,
  burnout: 4,
  depressive_verstimmung: 4,
  angst_panik: 5,
  selbstwert_selbstliebe: 4,
  emotionales_essen: 4,
  krankheit_psychosomatik: 4,
  angehoerige: 0,
  sexualitaet: 4,
  trauer: 4,
},
},

{
    id: "267d9682-acf8-4f90-9873-69cad7a05d11",
  name: "Jennifer",
  role: "Psychologin, Systemischer Coach",
  qualificationLevel: 4,
  image: "https://mypoise.de/wp-content/uploads/2022/11/Screen-Shot-2022-11-22-at-09.59.06-700x700.png",
  video: "https://youtu.be/NwQ1ftS6YvM",
  short:
    "Ich unterstütze dich dabei, alte Beziehungsmuster zu erkennen, emotionale Trigger zu verstehen und neue Handlungsspielräume zu entwickeln.",
  themes: {
    beziehung: 3,
    selbstwert: 3,
    identität: 2,
    emotionale_regulation: 2,
    konflikt: 1,
  },
  keywords: [
    "beziehungsmuster","bindungsmuster","konflikte",
    "trigger","emotionale reaktionen",
    "selbstwert","selbstvertrauen",
    "identität","selbstbild",
    "systemisch","klar","strukturiert"
  ],
  preis_std: 160,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/aa848084588fd6e79f8f7056180a78ca0602df5ec8e305cfc50c600a36da43e6%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 4,
  beruf_ziele_orientierung: 2,
  stress: 4,
  burnout: 4,
  depressive_verstimmung: 4,
  angst_panik: 0,
  selbstwert_selbstliebe: 4,
  emotionales_essen: 0,
  krankheit_psychosomatik: 0,
  angehoerige: 0,
  sexualitaet: 0,
  trauer: 4,
},
},
{
    id: "7d82df90-9508-4179-ab48-758f341b49c7",
  name: "Judith",
  role: "Klinische Psychologin",
  qualificationLevel: 2,
  image: "https://mypoise.de/wp-content/uploads/2022/11/Judith_Gross-1300x1300.jpg",
  video: "https://youtu.be/-BBED_bocu0",
  short:
    "Ich unterstütze dich dabei, innere Belastung zu verstehen, einzuordnen und wieder mehr Stabilität & Leichtigkeit zu finden.",
  themes: {
    selbstwert: 3,
    stress: 3,
    depressive_verstimmung: 3,
    emotionales_essen: 3,
    angehoerige: 3,
    krankheit_psychosomatik: 3,
    beziehung_partnerschaft: 3,
    angst_panikattacken: 3,
    beruf_ziele_orientierung: 3,
    burnout: 3,
    trauer: 3,
    sexualitaet: 3,
  },
  keywords: [
    "selbstwert","selbstliebe","selbstvertrauen","selbstzweifel",
    "stress","überforderung","gedankenkreisen","schlafstörungen",
    "depressive verstimmung","erschöpfung","antriebslosigkeit",
    "emotionales essen","fressanfälle","binge",
    "angehörige","abgrenzung","selbstfürsorge",
    "psychosomatik","körper und psyche","diagnose",
    "beziehung","partnerschaft","trennung",
    "angst","panik","panikattacken",
    "beruf","job","entscheidungen","neuorientierung",
    "burnout","ausgebrannt",
    "trauer","verlust","abschied",
    "sexualität","lustlosigkeit","libido"
  ],
  preis_std: 170,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/75c37902f254fc6e9b8e4c73238eb7bd74d1e11a7709a144683a092097335781%40group.calendar.google.com/public/basic.ics",
 scores: {
  partnerschaft_beziehung: 4,
  beruf_ziele_orientierung: 4,
  stress: 4,
  burnout: 4,
  depressive_verstimmung: 4,
  angst_panik: 5,
  selbstwert_selbstliebe: 4,
  emotionales_essen: 4,
  krankheit_psychosomatik: 4,
  angehoerige: 4,
  sexualitaet: 4,
  trauer: 4,
},
},

{
    id: "f7edf9da-8fda-4682-b464-250fd84db0cf",
  name: "Julius",
  role: "Psychologe, Coach",
  qualificationLevel: 4,
  image: "https://mypoise.de/wp-content/uploads/2023/09/Poise_bild-1300x1300.jpg",
  video: "https://youtu.be/YNS5APSbV8Y",
  short:
    "Ich arbeite ressourcenorientiert und klar — wir finden gemeinsam praktikable Schritte, die sich nicht nur gut anhören, sondern wirklich funktionieren.",
  themes: {
    selbstwert: 1,
    stress: 3,
    depressive_verstimmung: 3,
    angehoerige: 1,
    krankheit_psychosomatik: 1,
    beziehung_partnerschaft: 1,
    angst_panikattacken: 1,
    beruf_ziele_orientierung: 3,
    burnout: 3,
  },
  keywords: [
    "beruf","job","karriere","entscheidungen","neuorientierung",
    "stress","gedankenkreisen","druck","schlafprobleme",
    "burnout","erschöpfung","ausgebrannt",
    "depressive verstimmung","krise","antriebslosigkeit",
    "angst","panik",
    "beziehung","konflikte",
    "ressourcenorientiert","klar","lösungsorientiert"
  ],
  preis_std: 160,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/8a00eded0b43b92f02470e3ee4791aee343a9e4226c20e758b5ba2cbca2ba0fc%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 1,
  beruf_ziele_orientierung: 4,
  stress: 4,
  burnout: 4,
  depressive_verstimmung: 4,
  angst_panik: 2,
  selbstwert_selbstliebe: 0,
  emotionales_essen: 0,
  krankheit_psychosomatik: 1,
  angehoerige: 1,
  sexualitaet: 0,
  trauer: 1,
},
},

{
    id: "bb7bce0f7-45be-427e-bca4-73386dbdc690",
  name: "Kristin",
  role: "Coach, Heilpraktikerin für Psychotherapie, Trauerbegleiterin",
  qualificationLevel: 5,
  image: "https://mypoise.de/wp-content/uploads/2024/01/202411_CG_LiliKristin_276-1300x1300.jpg",
  video: "https://youtu.be/z7LUAXxzW7I",
  short:
    "Ich begleite dich, wenn du Verlust erlebt hast — behutsam, würdevoll und klar.",
  themes: {
    trauer: 3,
    selbstwert: 1,
    depressive_verstimmung: 1,
  },
  keywords: [
    "trauer","verlust","abschied","fehlgeburt",
    "krise","traurigkeit","innere leere",
    "selbstwert","selbstzweifel",
    "würdevoll","halt","begleitung"
  ],
  preis_std: 110,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/693a5cd58448b0e4b9bd86d347a9efc125ed2e8967778fb8386e99c25e4d761b%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 0,
  beruf_ziele_orientierung: 0,
  stress: 0,
  burnout: 0,
  depressive_verstimmung: 1,
  angst_panik: 0,
  selbstwert_selbstliebe: 1,
  emotionales_essen: 0,
  krankheit_psychosomatik: 0,
  angehoerige: 0,
  sexualitaet: 0,
  trauer: 5,
},
},

{
    id: "efa57a23-9498-4c84-8ce2-28e6b65e3c16",
  name: "Kristin-Sofie",
  role: "Psychologin, Psychotherapeutin",
  qualificationLevel: 1,
  image: "https://mypoise.de/wp-content/uploads/2024/07/DSCF6979-1300x1300.jpg",
  video: "https://youtu.be/pExhqepTZRQ",
  short:
    "Ich begleite dich dabei, Klarheit über deine Gefühle zu bekommen und innere Stabilität aufzubauen — achtsam, ruhig und strukturiert.",
  themes: {
    selbstwert: 1,
    stress: 2,
    depressive_verstimmung: 3,
    emotionales_essen: 2,
    angehoerige: 3,
    krankheit_psychosomatik: 2,
    angst_panikattacken: 3,
    beruf_ziele_orientierung: 3,
    burnout: 3,
    trauer: 2,
  },
  keywords: [
    "depressive verstimmung","erschöpfung","antriebslosigkeit",
    "burnout","dauerstress","keine energie",
    "angst","panik","panikattacken",
    "stress","schlafprobleme","gedankenkreisen",
    "beruf","job","entscheidungen",
    "angehörige","abgrenzung","selbstfürsorge",
    "emotionales essen","binge",
    "trauer","verlust",
    "achtsam","ruhig","klar"
  ],
  preis_std: 160,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/0796b382bb757d367c469af13358ae1bba96756ee606c256bb1e5985cf7f4b82%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 0,
  beruf_ziele_orientierung: 4,
  stress: 5,
  burnout: 4,
  depressive_verstimmung: 4,
  angst_panik: 5,
  selbstwert_selbstliebe: 4,
  emotionales_essen: 2,
  krankheit_psychosomatik: 2,
  angehoerige: 4,
  sexualitaet: 0,
  trauer: 4,
},
},
{
    id: "4cc4ef80-0e59-4a1b-8e50-6964fea86e18",
  name: "Magdalena",
  role: "Klinische Psychologin, Kinder- und Jugendpsychologin",
  qualificationLevel: 2,
  image: "https://mypoise.de/wp-content/uploads/2023/01/Magdalena-e1672744279356-700x700.jpg",
  video: "https://youtu.be/b06MFP9AxTg",
  short:
    "Ich begleite Kinder, Jugendliche, Familien und Erwachsene durch schwierige Entwicklungs- und Lebensphasen.",
  themes: {
    familie: 3,
    beziehung: 3,
    entwicklung: 3,
    stress: 2,
    konfliktthemen: 2,
    trauer: 1,
  },
  keywords: [
    "familie","familienkonflikte","elternschaft","kindererziehung",
    "beziehung","paarprobleme","konflikte",
    "entwicklung","lebensphasen","übergänge",
    "stress","überforderung",
    "trauer","verlust",
    "systemisch","ressourcenorientiert","klar"
  ],
  preis_std: 150,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/857518f623143d4ba427588f9c5bf2d690fd3082137a06298b53c289d3046fb1%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 4,
  beruf_ziele_orientierung: 2,
  stress: 4,
  burnout: 2,
  depressive_verstimmung: 2,
  angst_panik: 4,
  selbstwert_selbstliebe: 4,
  emotionales_essen: 2,
  krankheit_psychosomatik: 4,
  angehoerige: 4,
  sexualitaet: 0,
  trauer: 4,
},
},

{
    id: "5cdad0d4-7859-4487-b6b0-72fc07897060",
  name: "Marleen",
  role: "Ärztin, Psychotherapeutin",
  qualificationLevel: 1,
  image: "https://mypoise.de/wp-content/uploads/2022/11/Foto-Homepage-1300x1300.jpg",
  video: "https://youtu.be/yXHYgCmN2ug",
  short:
    "Ich verbinde medizinische Erfahrung, Psychotherapie und Kommunikation – ganzheitlich und reflektiert.",
  themes: {
    psychosomatik: 3,
    stress: 3,
    depressive_verstimmung: 2,
    burnout: 2,
    selbstführung: 2,
    angst_panik: 1,
  },
  keywords: [
    "psychosomatik","körperliche symptome","schmerzen ohne befund",
    "stress","überlastung","anspannung",
    "depressive verstimmung","erschöpfung",
    "burnout","ausgebrannt",
    "selbstführung","klarheit",
    "medizinisch","ganzheitlich"
  ],
  preis_std: 160,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/f04835be069493481a3237bc58af0993bebf5ebf93267c8be3a1c2b77ba54800%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 4,
  beruf_ziele_orientierung: 2,
  stress: 4,
  burnout: 2,
  depressive_verstimmung: 2,
  angst_panik: 0,
  selbstwert_selbstliebe: 2,
  emotionales_essen: 4,
  krankheit_psychosomatik: 2,
  angehoerige: 4,
  sexualitaet: 2,
  trauer: 0,
},
},

{
    id: "cf0f05ee-d1a2-44cd-9dfa-468f0578db40",
  name: "Marisa",
  role: "Psychologin, Psychotherapeutin",
  qualificationLevel: 1,
  image: "https://mypoise.de/wp-content/uploads/2022/12/IMG_9908-e1669989498337-700x700.jpeg",
  video: "https://youtu.be/ge-l5t2V5WM",
  short:
    "Ich unterstütze dich darin, deine eigenen Bedürfnisse ernst zu nehmen, Grenzen zu setzen und deinen Weg selbstbewusst zu gehen.",
  themes: {
    selbstwert: 3,
    beziehung: 3,
    grenzsetzung: 3,
    depressive_verstimmung: 2,
    stress: 2,
    identität: 1,
  },
  keywords: [
    "selbstwert","selbstvertrauen","nicht genug sein",
    "grenzen","abgrenzung","nein sagen",
    "beziehung","beziehungsprobleme","emotionale abhängigkeit",
    "depressive verstimmung","erschöpfung",
    "stress","überforderung",
    "ermutigend","stärkend","klar"
  ],
  preis_std: 160,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/a68d390ae0f3766da51d30eb7beab68d400dbbedae7343247cf2e87a57ab0fde%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 1,
  beruf_ziele_orientierung: 4,
  stress: 4,
  burnout: 4,
  depressive_verstimmung: 4,
  angst_panik: 4,
  selbstwert_selbstliebe: 1,
  emotionales_essen: 2,
  krankheit_psychosomatik: 2,
  angehoerige: 2,
  sexualitaet: 0,
  trauer: 4,
},
},

{
    id: "b314c5c6a-df29-4703-961c-8ea9bf01f7ba",
  name: "Sophie",
  role: "Psychologin, Heilpraktikerin für Psychotherapie",
  qualificationLevel: 3,
  image: "https://mypoise.de/wp-content/uploads/2022/11/Foto-sophie-crop-1-e1668080175188.png",
  video: "https://youtu.be/OA4nNWg1nq4",
  short:
    "Ich helfe dir, deine Geschichte zu verstehen und emotionale Muster liebevoll zu verändern.",
  themes: {
    identität: 3,
    innere_anteile: 3,
    selbstmitgefühl: 3,
    depressive_verstimmung: 2,
    beziehung: 2,
  },
  keywords: [
    "identität","selbstbild","wer bin ich",
    "innere anteile","inneres kind","innere konflikte",
    "selbstmitgefühl","selbstannahme",
    "depressive verstimmung","innere leere",
    "beziehung","bindung",
    "achtsam","tiefgehend","biografisch"
  ],
  preis_std: 200,
  preis_ermaessigt: 150,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/7de0d517cd8d5ca144fdca0b7c64c96550a43b9fdf0a6071e44bc8b4437aabae%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 4,
  beruf_ziele_orientierung: 4,
  stress: 4,
  burnout: 1,
  depressive_verstimmung: 4,
  angst_panik: 1,
  selbstwert_selbstliebe: 4,
  emotionales_essen: 0,
  krankheit_psychosomatik: 0,
  angehoerige: 4,
  sexualitaet: 1,
  trauer: 4,
},
},
{
    id: "bbbd26c7-3b69-4afc-b730-9390ab8fcb7b",
  name: "Yanina",
  role: "Psychologin, Psychotherapeutin",
  qualificationLevel: 1,
  image: "https://mypoise.de/wp-content/uploads/2024/11/IMG_7943-scaled-e1732804924432-1022x1024.jpg",
  video: "https://youtu.be/2axjVpI5vus",
  short:
    "Ich begleite dich fundiert, tiefenpsychologisch und klar durch emotionale Prozesse.",
  themes: {
    tiefenpsychologie: 3,
    beziehung: 3,
    identität: 3,
    selbstwert: 2,
    depressive_verstimmung: 2,
    angst_panik: 1,
  },
  keywords: [
    "tiefenpsychologie","unbewusste muster","frühe prägungen",
    "beziehung","bindung","beziehungsdynamiken",
    "identität","selbstbild","innere konflikte",
    "selbstwert","selbstzweifel",
    "depressive verstimmung","innere leere",
    "therapeutisch","klar","sicherer rahmen"
  ],
  preis_std: 180,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/cf502bdfe6fe6de7fcfe7634f4dab305baaa01a1c04adf21781e4949ad6c0a62%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 4,
  beruf_ziele_orientierung: 2,
  stress: 4,
  burnout: 2,
  depressive_verstimmung: 2,
  angst_panik: 5,
  selbstwert_selbstliebe: 4,
  emotionales_essen: 2,
  krankheit_psychosomatik: 0,
  angehoerige: 2,
  sexualitaet: 2,
  trauer: 0,
},
},

  {
      id: "50a3650b-658d-4907-8091-2acf7662e40f",
  name: "Livia",
  role: null,
  qualificationLevel: 0,
  image: null,
  video: null,
  email: null,
  short: null,
  themes: {},
  keywords: [],
  preis_std: null,
  preis_ermaessigt: null,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/db443a1af4e04dfa8a1a1dee40d50b7d273b761ca4cf1ed19615759fd9871c24%40group.calendar.google.com/public/basic.ics",
  scores: {
    partnerschaft_beziehung: 5,
    beruf_ziele_orientierung: 0,
    stress: 0,
    burnout: 0,
    depressive_verstimmung: 0,
    angst_panik: 0,
    selbstwert_selbstliebe: 0,
    emotionales_essen: 0,
    krankheit_psychosomatik: 0,
    angehoerige: 0,
    sexualitaet: 1,
    trauer: 4,
  },
},
{
    id: "22b71ea3-9a49-42e9-bee1-f7d4f47b186c",
  name: "Linda",
  role: null,
  qualificationLevel: 0,
  image: null,
  video: null,
  email: null,
  short: null,
  themes: {},
  keywords: [],
  preis_std: null,
  preis_ermaessigt: null,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/4dbd40b318e4ef7c265d28ac328a52649a0022eb6cf9979ae10162d3c0fdcb63%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 5,
  beruf_ziele_orientierung: 0,
  stress: 4,
  burnout: 0,
  depressive_verstimmung: 0,
  angst_panik: 0,
  selbstwert_selbstliebe: 4,
  emotionales_essen: 0,
  krankheit_psychosomatik: 0,
  angehoerige: 2,
  sexualitaet: 2,
  trauer: 4,
},
},
{
    id: "48ead819-0493-4fa0-a258-93d572266b30",
  name: "Vivienne",
  role: null,
  qualificationLevel: 0,
  image: null,
  video: null,
  email: null,
  short: null,
  themes: {},
  keywords: [],
  preis_std: null,
  preis_ermaessigt: null,
   status: "frei",
  ics: "https://calendar.google.com/calendar/ical/fb1bf38a76bb815324618d7f9c9638e8df87705c53711e7441ce17f69b46f771%40group.calendar.google.com/public/basic.ics",
scores: {
  partnerschaft_beziehung: 0,
  beruf_ziele_orientierung: 0,
  stress: 0,
  burnout: 0,
  depressive_verstimmung: 0,
  angst_panik: 0,
  selbstwert_selbstliebe: 0,
  emotionales_essen: 4,
  krankheit_psychosomatik: 0,
  angehoerige: 0,
  sexualitaet: 0,
  trauer: 0,
},
},
{
  id: "79db9444-4abd-49a3-ace1-e52fdaed8ad0",
  name: "Test Therapeut",
  role: "Psychologe (Test)",
  qualificationLevel: 0,
  image: "https://mypoise.de/wp-content/uploads/2026/02/Bildschirmfoto-2026-02-02-um-04.22.00.png",
  video: null,
  email: "sebastian.kickinger@icloud.com",
  short: "Interner Test-Therapeut für Dashboard-Tests.",
  themes: {},
  keywords: [],
  preis_std: 180,
  preis_ermaessigt: 120,
  status: "frei",
  ics: "https://calendar.google.com/calendar/ical/f388af50de7d7a07cc0e9418dcd34727ba22684ad8de3f73d032f32965c4c1d6%40group.calendar.google.com/public/basic.ics",
  scores: {
    partnerschaft_beziehung: 4,
    beruf_ziele_orientierung: 4,
    stress: 4,
    burnout: 4,
    depressive_verstimmung: 4,
    angst_panik: 4,
    selbstwert_selbstliebe: 4,
    emotionales_essen: 4,
    krankheit_psychosomatik: 4,
    angehoerige: 4,
    sexualitaet: 4,
    trauer: 0,
  },
},];
