export const teamData = [
  {
    name: "Ann",
    role: "Coach, Heilpraktikerin für Psychotherapie, Hypnose Coach",
    image:
      "https://mypoise.de/wp-content/uploads/2023/01/DSC_0007-copy-2-1300x1300.jpg",
    video: "https://youtu.be/rWhc4JvVmaw",
    short:
      "Begleitung bei innerer Anspannung, Unsicherheit, Emotionsregulation und Stärkung der persönlichen Handlungsfähigkeit.",

    scores: {
      partnerschaft_beziehung: 4,
      beruf_ziele_orientierung: 2,
      emotionales_essen: 2,
      depressive_verstimmung: 2,
      stress: 4,
      burnout: 2,
      selbstwert_selbstliebe: 4,
      angst_panik: 2,
      krankheit_psychosomatik: 2,
      angehoerige: 2,
      sexualitaet: 0,
      trauer: 2,
    },
  },

  {
    name: "Yanina",
    image: "/team/yanina.jpg",
    scores: {
      partnerschaft_beziehung: 5,
      beruf_ziele_orientierung: 2,
      emotionales_essen: 2,
      depressive_verstimmung: 2,
      stress: 4,
      burnout: 2,
      selbstwert_selbstliebe: 4,
      angst_panik: 4,
      krankheit_psychosomatik: 2,
      angehoerige: 2,
      sexualitaet: 2,
      trauer: 2,
    },
  },

  {
    name: "Gerhard",
    image: "/team/gerhard.jpg",
    scores: {
      partnerschaft_beziehung: 1,
      beruf_ziele_orientierung: 5,
      emotionales_essen: 4,
      depressive_verstimmung: 4,
      stress: 4,
      burnout: 4,
      selbstwert_selbstliebe: 4,
      angst_panik: 4,
      krankheit_psychosomatik: 2,
      angehoerige: 1,
      sexualitaet: 1,
      trauer: 2,
    },
  },

  {
    name: "Marisa",
    image: "/team/marisa.jpg",
    scores: {
      partnerschaft_beziehung: 2,
      beruf_ziele_orientierung: 4,
      emotionales_essen: 2,
      depressive_verstimmung: 4,
      stress: 4,
      burnout: 4,
      selbstwert_selbstliebe: 1,
      angst_panik: 4,
      krankheit_psychosomatik: 2,
      angehoerige: 2,
      sexualitaet: 0,
      trauer: 4,
    },
  },

  {
    name: "Judith",
    image: "/team/judith.jpg",
    scores: {
      partnerschaft_beziehung: 4,
      beruf_ziele_orientierung: 4,
      emotionales_essen: 4,
      depressive_verstimmung: 4,
      stress: 4,
      burnout: 4,
      selbstwert_selbstliebe: 4,
      angst_panik: 4,
      krankheit_psychosomatik: 4,
      angehoerige: 4,
      sexualitaet: 4,
      trauer: 4,
    },
  },

  {
    name: "Sophie",
    image: "/team/sophie.jpg",
    scores: {
      partnerschaft_beziehung: 2,
      beruf_ziele_orientierung: 4,
      emotionales_essen: 0,
      depressive_verstimmung: 2,
      stress: 4,
      burnout: 1,
      selbstwert_selbstliebe: 4,
      angst_panik: 2,
      krankheit_psychosomatik: 0,
      angehoerige: 4,
      sexualitaet: 1,
      trauer: 2,
    },
  },

  {
    name: "Livia",
    image: "/team/livia.jpg",
    scores: {
      partnerschaft_beziehung: 5,
      beruf_ziele_orientierung: 0,
      emotionales_essen: 0,
      depressive_verstimmung: 0,
      stress: 4,
      burnout: 4,
      selbstwert_selbstliebe: 4,
      angst_panik: 0,
      krankheit_psychosomatik: 0,
      angehoerige: 2,
      sexualitaet: 2,
      trauer: 4,
    },
  },

  {
    name: "Linda",
    image: null,
    role: null,
    short: null,
    long: null,
    video: null,

    // Scores können später ergänzt werden
    scores: {
      partnerschaft_beziehung: 0,
      beruf_ziele_orientierung: 0,
      emotionales_essen: 0,
      depressive_verstimmung: 0,
      stress: 0,
      burnout: 0,
      selbstwert_selbstliebe: 0,
      angst_panik: 0,
      krankheit_psychosomatik: 0,
      angehoerige: 0,
      sexualitaet: 0,
      trauer: 0,
    },
  },
];
